R: R-4.3.2
packages:
  abind: 1.4-8
  AER: 1.2-14
  askpass: 1.2.0
  backports: 1.5.0
  base64enc: 0.1-3
  bit: 4.5.0
  bit64: 4.5.2
  blob: 1.2.4
  brio: 1.1.5
  broom: 1.0.7
  bslib: 0.6.1
  BWStest: 0.2.3
  cachem: 1.0.8
  callr: 3.7.6
  car: 3.1-3
  carData: 3.0-5
  cellranger: 1.1.0
  checkmate: 2.3.2
  cli: 3.6.2
  clipr: 0.8.0
  colorspace: 2.1-1
  conflicted: 1.2.0
  corrplot: '0.95'
  covr: 3.6.4
  cowplot: 1.1.3
  cpp11: 0.5.0
  crayon: 1.5.3
  curl: 5.2.3
  data.table: 1.16.0
  DBI: 1.2.3
  dbplyr: 2.5.0
  Deriv: 4.1.6
  desc: 1.4.3
  DescTools: 0.99.59
  diffobj: 0.3.5
  digest: 0.6.34
  doBy: 4.6.24
  dplyr: 1.1.4
  dtplyr: 1.3.1
  e1071: 1.7-16
  ellipsis: 0.3.2
  evaluate: 1.0.3
  evd: 2.3-7.1
  Exact: '3.3'
  expm: 1.0-0
  fansi: 1.0.6
  farver: 2.1.2
  fastmap: 1.1.1
  fitdistrplus: 1.2-1
  fontawesome: 0.5.2
  forcats: 1.0.0
  foreach: 1.5.2
  Formula: 1.2-5
  fs: 1.6.3
  gargle: 1.5.2
  generics: 0.1.3
  ggplot2: 3.5.1
  ggsignif: 0.6.4
  gld: 2.6.7
  glmnet: 4.1-8
  glue: 1.7.0
  gmp: 0.7-5
  googledrive: 2.1.1
  googlesheets4: 1.1.1
  gridExtra: '2.3'
  gtable: 0.3.5
  haven: 2.5.4
  highr: '0.10'
  hms: 1.1.3
  htmltools: 0.5.7
  httr: 1.4.7
  ids: 1.0.1
  installr: 0.23.4
  isoband: 0.2.7
  iterators: 1.0.14
  jquerylib: 0.1.4
  jsonlite: 1.8.8
  kableExtra: 1.4.0
  knitr: '1.45'
  kSamples: 1.2-10
  labeling: 0.4.3
  lazyeval: 0.2.2
  leaps: '3.2'
  lifecycle: 1.0.4
  lmboot: 0.0.1
  lme4: 1.1-36
  lmom: '3.2'
  lmtest: 0.9-40
  lubridate: 1.9.3
  magrittr: 2.0.3
  MatrixModels: 0.5-3
  memoise: 2.0.1
  microbenchmark: 1.5.0
  mime: '0.12'
  minqa: 1.2.8
  modelr: 0.1.11
  multcomp: 1.4-26
  multcompView: 0.1-10
  munsell: 0.5.1
  mvtnorm: 1.3-2
  nloptr: 2.1.1
  numDeriv: 2016.8-1.1
  openssl: 2.2.2
  pbkrtest: 0.5.3
  pillar: 1.9.0
  pkgbuild: 1.4.6
  pkgconfig: 2.0.3
  pkgload: 1.4.0
  PKNCA: 0.11.0
  plyr: 1.8.9
  PMCMRplus: 1.9.12
  praise: 1.0.0
  prettyunits: 1.2.0
  processx: 3.8.4
  progress: 1.2.3
  proxy: 0.4-27
  ps: 1.8.0
  purrr: 1.0.2
  quantreg: '5.99'
  R6: 2.5.1
  ragg: 1.3.3
  rappdirs: 0.3.3
  rbibutils: '2.3'
  RColorBrewer: 1.1-3
  Rcpp: 1.0.13-1
  RcppEigen: 0.3.4.0.2
  Rdpack: 2.6.3
  readr: 2.1.5
  readxl: 1.4.3
  reformulas: 0.4.0
  rematch: 2.0.0
  rematch2: 2.1.2
  reprex: 2.1.1
  reshape2: 1.4.4
  rex: 1.2.1
  rlang: 1.1.3
  rmarkdown: '2.25'
  Rmpfr: 1.0-0
  rootSolve: 1.8.2.4
  rprojroot: 2.0.4
  rstatix: 0.7.2
  rstudioapi: 0.16.0
  rvest: 1.0.4
  sandwich: 3.1-1
  sass: 0.4.8
  scales: 1.3.0
  selectr: 0.4-2
  shape: 1.4.6.1
  SparseM: 1.84-2
  stringi: 1.8.3
  stringr: 1.5.1
  SuppDists: 1.1-9.8
  svglite: 2.1.3
  sys: 3.4.2
  systemfonts: 1.2.2
  testthat: 3.2.3
  textshaping: 0.4.0
  TH.data: 1.1-2
  tibble: 3.2.1
  tidyr: 1.3.1
  tidyselect: 1.2.1
  tidyverse: 2.0.0
  timechange: 0.3.0
  tinytex: '0.49'
  tzdb: 0.4.0
  utf8: 1.2.4
  uuid: 1.2-1
  vctrs: 0.6.5
  viridisLite: 0.4.2
  vroom: 1.6.5
  waldo: 0.6.1
  withr: 3.0.2
  xfun: '0.41'
  xml2: 1.3.6
  yaml: 2.3.8
  zoo: 1.8-12
  base: 4.3.2
  boot: 1.3-28.1
  class: 7.3-22
  cluster: 2.1.4
  codetools: 0.2-19
  compiler: 4.3.2
  datasets: 4.3.2
  foreign: 0.8-85
  graphics: 4.3.2
  grDevices: 4.3.2
  grid: 4.3.2
  KernSmooth: 2.23-22
  lattice: 0.21-9
  MASS: 7.3-60
  Matrix: 1.6-1.1
  methods: 4.3.2
  mgcv: 1.9-0
  nlme: 3.1-163
  nnet: 7.3-19
  parallel: 4.3.2
  rpart: 4.1.21
  spatial: 7.3-17
  splines: 4.3.2
  stats: 4.3.2
  stats4: 4.3.2
  survival: 3.5-7
  tcltk: 4.3.2
  tools: 4.3.2
  translations: 4.3.2
  utils: 4.3.2
